
services:
  # Service Backend Express API
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432        # Di dalam jaringan Docker, port PostgreSQL tetap 5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=super_secret_production_key_123
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  # Service Database PostgreSQL
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - "5433:5432"         # Port 5433 dipetakan ke luar untuk koneksi TablePlus
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service Cache Redis
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: